package zhijiaoyun

import (
	"Gozhijiao/request"
	"crypto/md5"
	"encoding/json"
	"fmt"
	"time"
)

type Zhijiao struct {
	User string
	Pass string
}

type AutoGenerated struct {
	AppVersionInfo struct {
		VersionCode string `json:"VersionCode"`
	} `json:"appVersionInfo"`
}

func New(user, pass string) *Zhijiao {
	return &Zhijiao{
		User: user,
		Pass: pass,
	}
}

// 登录
func (Z *Zhijiao) Login() {
	var (
		emit             string = fmt.Sprint(time.Now().Unix(), "000")
		device           string = "Xiaomi Redmi K20 Pro"
		deviceApiVerison string = "10"
		appVersion       string = getAppVeriosn()
		url                     = "https://zjyapp.icve.com.cn/newMobileAPI/MobileLogin/newSignIn"
		header                  = map[string]string{"Content-Type": "application/x-www-form-urlencoded", "emit": emit, "device": getDeviceEncryption(device, deviceApiVerison, appVersion, emit)}
		data                    = map[string]string{"clientId": "d902c875d5f34c0f93362139f5af0c4c", "sourceType": "2", "userPwd": Z.Pass, "userName": Z.User, "appVersion": appVersion, "equipmentAppVersion": appVersion, "equipmentApiVersion": deviceApiVerison, "equipmentModel": device}
	)
	// fmt.Println(getDeviceEncryption("Xiaomi Redmi K20 Pro", "10", "2.8.42", "1646975351000"))
	request.Post(url, data, header)
}
func (z *Zhijiao) s1() {

}

func getAppVeriosn() string {
	s := request.Get("https://zjy2.icve.com.cn/portal/AppVersion/getLatestVersionInfo")
	p := &AutoGenerated{}
	err := json.Unmarshal(s, p)
	if err != nil {
		panic(err)
	}
	return p.AppVersionInfo.VersionCode
}

func getDeviceEncryption(args ...string) string {
	// var md5str1 string
	var tmp string
	for i, v := range args {
		if i == 0 {
			tmp = md5str(v)
			continue
		}
		tmp = fmt.Sprintf("%s%s", tmp, args[i])
		tmp = md5str(tmp)
	}
	return tmp
}
func md5str(str string) string {
	data := []byte(str)
	has := md5.Sum(data)
	md5str1 := fmt.Sprintf("%x", has)
	return md5str1
}
